<a href="https://colab.research.google.com/github/DharmeshRV/Hotel-Booking-Analysis/blob/main/Hotel_Booking_Analysis_Capstone_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <b> Have you ever wondered when the best time of year to book a hotel room is? Or the optimal length of stay in order to get the best daily rate? What if you wanted to predict whether or not a hotel was likely to receive a disproportionately high number of special requests? This hotel booking dataset can help you explore those questions!

## <b>This data set contains booking information for a city hotel and a resort hotel, and includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things. All personally identifying information has been removed from the data. </b>

## <b> Explore and analyze the data to discover important factors that govern the bookings. </b>

In [1]:
# first import some important libraries:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from datetime import datetime

Now, I mount the drive to load the hotel data and create a dtaframe.

In [2]:
# mount the drive to get the data.

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# copying the file path create the hotel dataframe
path='/content/drive/MyDrive/Colab Notebooks/Almabetter_Data Science/Capstone Projects/Hotel Booking Analysis - Dharmesh Kumar/Hotel Bookings.csv'
hotel_df=pd.read_csv(path)

A glance at newly created dataframe

In [4]:
hotel_df.head()

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  deposit_type  \
0                        0                     0       2  ...    No Deposit   
1                        0                     0       2  ...    No Deposit   
2                        0                     1       1  ...    No Deposit   
3                        0                     1       1  ...    No Deposit   
4                        0                     2       2  ...    No Deposit   

   agent company days_in_waiting_list customer_type   adr  \
0    NaN     NaN                    0     Transient   0.0   
1    NaN     NaN                    0     Transient   0.0   
2    NaN     NaN                    0     Transient  75.0   
3  304.0     NaN                    0     Transient  75.0   
4  240.0     NaN                    0     Transient  98.0   

   required_car_parking_spaces  total_of_special_requests  reservation_status  \
0                            0                          0           Check-Out   
1                            0                          0           Check-Out   
2                            0                          0           Check-Out   
3                            0                          0           Check-Out   
4                            0                          1           Check-Out   

  reservation_status_date  
0              2015-07-01  
1              2015-07-01  
2              2015-07-02  
3              2015-07-02  
4              2015-07-03  

[5 rows x 32 columns]

In [5]:
hotel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

Now we get unique values in the columns with categorical data to undersrand the data stored in these columns.

In [6]:
# unique hotel types:
hotel_df["hotel"].unique()

array(['Resort Hotel', 'City Hotel'], dtype=object)

In [7]:
# years in which bookings are made:
hotel_df["arrival_date_year"].unique()

array([2015, 2016, 2017])

In [8]:
# months in which guests arrive:
hotel_df["arrival_date_month"].unique()

array(['July', 'August', 'September', 'October', 'November', 'December',
       'January', 'February', 'March', 'April', 'May', 'June'],
      dtype=object)

In [9]:
# values in 'is_repeated_guest' column:
hotel_df["is_repeated_guest"].unique()

array([0, 1])

In [10]:
# unique meal types in the hotels:
hotel_df["meal"].unique()

array(['BB', 'FB', 'HB', 'SC', 'Undefined'], dtype=object)

In [11]:
# unique countries of origin:
hotel_df["country"].unique()

array(['PRT', 'GBR', 'USA', 'ESP', 'IRL', 'FRA', nan, 'ROU', 'NOR', 'OMN',
       'ARG', 'POL', 'DEU', 'BEL', 'CHE', 'CN', 'GRC', 'ITA', 'NLD',
       'DNK', 'RUS', 'SWE', 'AUS', 'EST', 'CZE', 'BRA', 'FIN', 'MOZ',
       'BWA', 'LUX', 'SVN', 'ALB', 'IND', 'CHN', 'MEX', 'MAR', 'UKR',
       'SMR', 'LVA', 'PRI', 'SRB', 'CHL', 'AUT', 'BLR', 'LTU', 'TUR',
       'ZAF', 'AGO', 'ISR', 'CYM', 'ZMB', 'CPV', 'ZWE', 'DZA', 'KOR',
       'CRI', 'HUN', 'ARE', 'TUN', 'JAM', 'HRV', 'HKG', 'IRN', 'GEO',
       'AND', 'GIB', 'URY', 'JEY', 'CAF', 'CYP', 'COL', 'GGY', 'KWT',
       'NGA', 'MDV', 'VEN', 'SVK', 'FJI', 'KAZ', 'PAK', 'IDN', 'LBN',
       'PHL', 'SEN', 'SYC', 'AZE', 'BHR', 'NZL', 'THA', 'DOM', 'MKD',
       'MYS', 'ARM', 'JPN', 'LKA', 'CUB', 'CMR', 'BIH', 'MUS', 'COM',
       'SUR', 'UGA', 'BGR', 'CIV', 'JOR', 'SYR', 'SGP', 'BDI', 'SAU',
       'VNM', 'PLW', 'QAT', 'EGY', 'PER', 'MLT', 'MWI', 'ECU', 'MDG',
       'ISL', 'UZB', 'NPL', 'BHS', 'MAC', 'TGO', 'TWN', 'DJI', 'STP',
       'KNA', 'E

In [12]:
# types of market segments:
hotel_df["market_segment"].unique()

array(['Direct', 'Corporate', 'Online TA', 'Offline TA/TO',
       'Complementary', 'Groups', 'Undefined', 'Aviation'], dtype=object)

In [13]:
# unique distribution channels:
hotel_df["distribution_channel"].unique()

array(['Direct', 'Corporate', 'TA/TO', 'Undefined', 'GDS'], dtype=object)

In [14]:
# types of rooms reserved by guests:
hotel_df["reserved_room_type"].unique()

array(['C', 'A', 'D', 'E', 'G', 'F', 'H', 'L', 'P', 'B'], dtype=object)

In [15]:
# types of rooms assigned by hotels:
hotel_df["assigned_room_type"].unique()

array(['C', 'A', 'D', 'E', 'G', 'F', 'I', 'B', 'H', 'P', 'L', 'K'],
      dtype=object)

In [16]:
# number of booking changes:
hotel_df["booking_changes"].unique()

array([ 3,  4,  0,  1,  2,  5, 17,  6,  8,  7, 10, 16,  9, 13, 12, 20, 14,
       15, 11, 21, 18])

In [17]:
# unique deposit types:
hotel_df["deposit_type"].unique()

array(['No Deposit', 'Refundable', 'Non Refund'], dtype=object)

In [26]:
# type of agents:
hotel_df['agent'].unique()

array([ nan, 304., 240., 303.,  15., 241.,   8., 250., 115.,   5., 175.,
       134., 156., 243., 242.,   3., 105.,  40., 147., 306., 184.,  96.,
         2., 127.,  95., 146.,   9., 177.,   6., 143., 244., 149., 167.,
       300., 171., 305.,  67., 196., 152., 142., 261., 104.,  36.,  26.,
        29., 258., 110.,  71., 181.,  88., 251., 275.,  69., 248., 208.,
       256., 314., 126., 281., 273., 253., 185., 330., 334., 328., 326.,
       321., 324., 313.,  38., 155.,  68., 335., 308., 332.,  94., 348.,
       310., 339., 375.,  66., 327., 387., 298.,  91., 245., 385., 257.,
       393., 168., 405., 249., 315.,  75., 128., 307.,  11., 436.,   1.,
       201., 183., 223., 368., 336., 291., 464., 411., 481.,  10., 154.,
       468., 410., 390., 440., 495., 492., 493., 434.,  57., 531., 420.,
       483., 526., 472., 429.,  16., 446.,  34.,  78., 139., 252., 270.,
        47., 114., 301., 193., 182., 135., 350., 195., 352., 355., 159.,
       363., 384., 360., 331., 367.,  64., 406., 16

In [27]:
hotel_df['company'].unique()

array([ nan, 110., 113., 270., 178., 240., 154., 144., 307., 268.,  59.,
       204., 312., 318.,  94., 174., 274., 195., 223., 317., 281., 118.,
        53., 286.,  12.,  47., 324., 342., 373., 371., 383.,  86.,  82.,
       218.,  88.,  31., 397., 392., 405., 331., 367.,  20.,  83., 416.,
        51., 395., 102.,  34.,  84., 360., 394., 457., 382., 461., 478.,
       386., 112., 486., 421.,   9., 308., 135., 224., 504., 269., 356.,
       498., 390., 513., 203., 263., 477., 521., 169., 515., 445., 337.,
       251., 428., 292., 388., 130., 250., 355., 254., 543., 531., 528.,
        62., 120.,  42.,  81., 116., 530., 103.,  39.,  16.,  92.,  61.,
       501., 165., 291., 290.,  43., 325., 192., 108., 200., 465., 287.,
       297., 490., 482., 207., 282., 437., 225., 329., 272.,  28.,  77.,
       338.,  72., 246., 319., 146., 159., 380., 323., 511., 407., 278.,
        80., 403., 399.,  14., 137., 343., 346., 347., 349., 289., 351.,
       353.,  54.,  99., 358., 361., 362., 366., 37

In [18]:
# types of customers
hotel_df["customer_type"].unique()

array(['Transient', 'Contract', 'Transient-Party', 'Group'], dtype=object)

In [19]:
# unique reservation stasus:
hotel_df["reservation_status"].unique()

array(['Check-Out', 'Canceled', 'No-Show'], dtype=object)

In [20]:
# values in 'is_canceled' column:
hotel_df["is_canceled"].unique()

array([0, 1])

Understanding the column data

1. hotel: type of hotels
2. is_canceled: canceled or not
3. lead_time: no. of days before actual arrival in the hotel
4. arrival_date_year: year of booking
5. arrival_date_month: month of booking
6. arrival_date_week_number: week number of the year in which
   booking
7.arrival_date_day_of_month: arrival month date             
8. stays_in_weekend_nights: no. of weekends guest stayed
9. stays_in_week_nights: no. of weekdays guest stayed               
10. adults                                 
11. children                               
12. babies                                 
13. meal:   BB – Bed & Breakfast,     HB – only two meals including breakfast meal,     FB – breakfast, lunch, and dinner
14. country                              
15. market_segment:   TA: Travel agents,   TO: Tour operators                       
16. distribution_channel                 
17. is_repeated_guest                    
18. previous_cancellations: cancellation in past                 
19. previous_bookings_not_canceled: not cancelled in past        
20. reserved_room_type                     
21. assigned_room_type                     
22. booking_changes                        
23. deposit_type                           
24. agent                              
25. company                           
26. days_in_waiting_list                   
27. customer_type                          
28. adr: average daily rate
29. required_car_parking_spaces            
30. total_of_special_requests              
31. reservation_status                     
32. reservation_status_date

In [21]:
# Now we can drop irrelevant columns
hotel_df.drop("arrival_date_week_number",inplace=True,axis=1)

Now it's time for data wrangling. Frist, let's fix null values in our dataset.

In [23]:
hotel_df.isnull().sum().sort_values(ascending=False)

company                           112593
agent                              16340
country                              488
children                               4
hotel                                  0
previous_bookings_not_canceled         0
reservation_status                     0
total_of_special_requests              0
required_car_parking_spaces            0
adr                                    0
customer_type                          0
days_in_waiting_list                   0
deposit_type                           0
booking_changes                        0
assigned_room_type                     0
reserved_room_type                     0
is_repeated_guest                      0
previous_cancellations                 0
is_canceled                            0
distribution_channel                   0
market_segment                         0
meal                                   0
babies                                 0
adults                                 0
stays_in_week_ni

In [28]:
# 'company' and 'agents' columns have large number of null values and they have float data so we fill them with 0.
hotel_df["company"].fillna(0, inplace=True)
hotel_df["agent"].fillna(0, inplace=True)

In [29]:
# there are some null values in 'country' column, we replace them with 'other'. we can also replace null values with the mode value as the datatype is 'object'. 
hotel_df["country"].fillna("other", inplace=True)

In [30]:
# 'children' column also have some null values and we will replace them with the median value.
hotel_df["children"].median()

0.0

In [32]:
# median values is 0
hotel_df["children"].fillna(hotel_df["children"].median(),inplace=True)

In [33]:
# the null values are fixed, let's see if there are any
hotel_df.isnull().sum().sort_values(ascending=False).head(5)

hotel                          0
previous_cancellations         0
reservation_status             0
total_of_special_requests      0
required_car_parking_spaces    0
dtype: int64

Data may have duplicated information so I check it as well.

In [34]:
# looking for duplicate entries. True shows duplicate row.
hotel_df.duplicated().value_counts()

False    87396
True     31994
dtype: int64

In [35]:
# we drop the duplicate rows
hotel_df.drop_duplicates(inplace=True, ignore_index=True)

Feature engineering...

In [36]:
# We have three different columns for adults, children and babies so we introduce a column for total guests.
hotel_df["total_guests"]=hotel_df["adults"]+hotel_df["children"]+hotel_df["babies"]

In [37]:
# stays_in_week_nights and stays_in_weekend_nights are the two columns for stays so we get the total stay
hotel_df['total_stay']=hotel_df['stays_in_week_nights'] +hotel_df['stays_in_weekend_nights'] 

In [38]:
# the date year, month and day are in different columns so we create  a column 'arrival_date'.
hotel_df["arrival_date"]=hotel_df["arrival_date_month"]+" "+hotel_df["arrival_date_day_of_month"].astype(str)+" "+hotel_df["arrival_date_year"].astype(str)
hotel_df["arrival_date"]=pd.to_datetime(hotel_df["arrival_date"])